#! /usr/bin/env python

from __future__ import print_function
import json

source_file='package.json'
target_file='version.txt'

with open(target_file, 'w') as version_file:
    with open(source_file) as json_data:
        d = json.load(json_data)
        version_file.write("VERSION=" + d['version'])